name: luizalabs-desafio-backend
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - ../..:/workspaces:cached
      # - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      TESTCONTAINERS_RYUK_DISABLED: "true" # Desabilita Ryuk temporariamente
    ports:
    - 3001:3000
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - 5434:5432

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest 
    restart: always
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    ports:
      - 8978:8978
 
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mock-products-server:
    image: wiremock/wiremock:3.12.1-1
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
      
volumes:
  postgres-data:
  cloudbeaver:
